# 1. Chọn hệ điều hành rút gọn có sẵn máy chủ web (Nginx)
FROM nginx:alpine

# 2. Chép mã nguồn (tập tin index.html) từ máy tính (máy của lập trình viên) vào đúng vị trí trong Image
COPY index.html /usr/share/nginx/html/index.html 
